### PR TITLE
Some suggestions

### PR DESCRIPTION
**Pull request by ghost**
I'd like to suggest something. For example:
*Add the ability to delete and recreate a release when pushing a new commit
*Auto-incrementation of project versions (this way in the future we will be able to implement a self-updating mechanism, receiving the release version as the stand does, but then the links in the README will become inactive)
Feel free to close this pull request if you don't need it, it's just a suggestion

### CODE REVIEW

**Comment by NiiV3AU** [comment]
Is this workflow fully automatic? I mean if I for example edit the README and push a commit by saving it, would it trigger a release/build? @xesdoog helped me with the worklfow beforehand, and I requestet him that it needs to be a manual trigger because I need to edit the Changelog befor releasing. Your Idea with the versioning is perfect, one thing less to edit manually. So if the workflow is manual and if the next release would be v1.0.2 after running it, I would merge your pr. Also I would appreciate if you could tell me what kind of token and what permmission I need to run it. I get this [Error](https://github.com/NiiV3AU/YMU/pull/4#issuecomment-2148505586) on release part of the action/workflow! Thanks in advance.

**Comment by xesdoog** [comment]
@NiiV3AU This is a good PR and the workflow is still manually launched so you should merge it but before you do we need to make some adjustments since we're already here:

@CringeArab ymu.exe needs the icon file to run otherwise it crashes so instead of uploading a single exe in the release, we need to upload a zip containing both the exe and the ico. if you could please edit this PR and add something like this under the build job right after the 'Create Binary' step: 
```yaml
  - name: Create Archive
      run: |
        New-Item -Path . -Name "YMU" -ItemType "directory"
        Copy-Item D:\a\YMU\\YMU\ymu.ico -Destination D:\a\YMU\YMU\YMU
        Copy-Item D:\a\YMU\YMU\dist\ymu.exe -Destination D:\a\YMU\YMU\YMU
        Compress-Archive -Path D:\a\YMU\YMU\YMU -DestinationPath D:\a\YMU\YMU\ymu.zip

  - name: Upload Archive
    uses: actions/upload-artifact@v4
      with:
        name: zipFile
        path: |
          ymu.zip
```
Then under 'Create Release' job, modify the 'Download Artifact' step to this:
```yaml
  - name: Download Archive
      uses: actions/download-artifact@v4
      with:
        name: zipFile
```
And finally at the very end of the file replace ymu.exe with ymu.zip

> what kind of token and what permmission I need to run it

@NiiV3AU You're getting the error because the workflow runner doesn't have permission to write to your repository, in this case publish or delete a release. All you need to do is create a Private Access Token following this [Github documentation](https://docs.github.com/en/enterprise-server@3.9/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens#creating-a-personal-access-token) and grant it read/write access to your repos. To learn more about scopes (permissions) [read this](https://docs.github.com/en/enterprise-server@3.9/apps/oauth-apps/building-oauth-apps/scopes-for-oauth-apps#available-scopes) before deciding which ones you want to grant in your PAT.
Note that you only have to create it. You don't have to specify it in the workflow file or anywhere else. Keep it somewhere safe just like a password.

**Comment by NiiV3AU** [comment]
Ok now I have a classic token with the "repo" permission. Im waiting, so you guys can do your polishing. Just let me know when I can merge this PR and I will do it asap!

**Comment by NiiV3AU** [comment]
grafik
grafik

**Comment by xesdoog** [comment]
What happened? 😅

**Comment by NiiV3AU** [comment]
Idk he just deleted his fork. What do we do now? Can you finish the workflow like you explained? I would do it myself but I just know I would mess it up. Sooo could you help me out one more time?
grafik

**Comment by xesdoog** [comment]
Of course ❤️

**Pull request closed without merging**
