### PR TITLE
[Code]: Better Inject Button Behavior + Self Update System

### PR DESCRIPTION
**Pull request by xesdoog**
**General**:
- Disabled resizing for all windows except the changelog window.
- Added self update for YMU. From now on, we will have to remember to edit **LOCAL_VER** with each update to ymu.py. The rest takes care of itself.
- Created a small function that simulates progress. It just fills a progress bar when we have no actual feedback to work with.
- Added a **Settings** tab that shows the current version and the self update button.

**Inject Tab**:
- I tried to make the process finding function loop but it kept causing the GUI to lag even when run in it's own separate thread. Therefore I've changed the Inject Button to act as a process scanner each time it is pressed.
- Added a delay after injection to see if the game is still running. If it is, the program says farewell and exits to free up resources (about 70MB of memory). If not, the program recognizes that the game crashed on injection. For now this serves no purpose but it can be used in the future to apply quick fixes to things that cause the game to crash (like deleting YimMenu's *cache* folder).

### CODE REVIEW

**Comment by xesdoog** [comment]
We should use a smaller splash screen image. The one we currently have is bigger than the main window but it should be either the same size or smaller.

**Comment by NiiV3AU** [comment]
Ive also done some stuff in the meanwhile, I made the hover over the links (more info/changelog) better by removing the pointing arrows while hovering and underlining the text. Also I made a "Open Directory"-Button which obviously open the DLLDIR in the explorer. I also had a Settings tab in mind but couldnt figure out what the user like to change, maybe the download chunk size?

**Comment by xesdoog** [comment]
> Ive also done some stuff in the meanwhile, I made the hover over the links (more info/changelog) better by removing the pointing arrows while hovering and underlining the text. Also I made a "Open Directory"-Button which obviously open the DLLDIR in the explorer.

I hope this PR didn't mess with your progress! If it did then I'm sorry I thought you were busy with something else. Do you have discord or something so we can communicate better?

> I also had a Settings tab in mind but couldnt figure out what the user like to change, maybe the download chunk size?

I honestly don't know why because I'm still not good with tkinter or customtkinter but I tried to add the ability to switch between light and dark mode under settings but light mode wasn't working. The code for it is quoted out at the bottom of the file but other than that I couldn't think of something else to add to the settings tab.

**Comment by xesdoog** [comment]
splash

@NiiV3AU I have 0 artistic talent but I think this is beautiful👌As for the size, as long as it's not bigger than the main window and not too small then it's fine. You definitely have good taste!

**Comment by NiiV3AU** [comment]
I cant view your linked image? Yeah I also have 0 artistic as you can see 💀, also not the tools to make a professional looking logo / splashscreen

**Comment by NiiV3AU** [comment]
GitHub has a built in IPlogger? 🥲 
grafik

**Comment by xesdoog** [comment]
> I cant view your linked image? 

It's just the same one you linked before

> Yeah I also have 0 artistic as you can see 💀, also not the tools to make a professional looking logo / splashscreen

But the ones you created are very nice. I sent this to a friend of mine and the first thing she said was: *Woo, fancy!* lol

> GitHub has a built in IPlogger?

Yeah I guess privacy is dead 💀 You can decline the invite though I just wanted you to share ownership of that repo

**Comment by NiiV3AU** [comment]
> But the ones you created are very nice. I sent this to a friend of mine and the first thing she said was: _Woo, fancy!_ lol

Probably in a sarcastic way haha the font just fitted to good with the loading aspect 😆 

> Yeah I guess privacy is dead 💀 You can decline the invite though I just wanted you to share ownership of that repo

No problem I dont care I mean its a isp and my ip changes from time to time due to dhcp and I mean the worst tha could happen is a ddos

**Comment by xesdoog** [comment]
Btw don't forget to increment LOCAL_VER in ymu.py before creating a new release. I have an idea in mind to make it fully automatic in the future by simply using GitHub Actions to create a version.txt file that holds the new tag of the new release and then combining it with the exe in a zip file.

**Comment by NiiV3AU** [comment]
> Btw don't forget to increment LOCAL_VER in ymu.py before creating a new release. 

Yeah forgot to change it to 1.0.3 

> I have an idea in mind to make it fully automatic in the future by simply using GitHub Actions to create a version.txt file that holds the new tag of the new release and then combining it with the exe in a zip file.

Nice Idea but I mean Im ok with needing to change it with each realease as I also need to edit the changelog manually as well. Also I added the directory button which contains two folder pngs (hover+normal) can I add these pngs in the pyinstaller command or do they need to exist in the "/icon/"-folder which would be a problem for the standalone exe we worked towards

**Comment by xesdoog** [comment]
> can I add these pngs in the pyinstaller command or do they need to exist in the "/icon/"-folder which would be a problem for the standalone exe we worked towards

if they are in their own folder then just add this to pyinstaller `--add-data "./folder_name;folder_name/"`
But most importantly when referencing them inside ymu.py always use the path function : `png1 = resource_path(r'./path-to-the-png')`

**Comment by NiiV3AU** [comment]
> > can I add these pngs in the pyinstaller command or do they need to exist in the "/icon/"-folder which would be a problem for the standalone exe we worked towards
> 
> if they are in their own folder then just add this to pyinstaller `--add-data "./folder_name;folder_name/"` But most importantly when referencing them inside ymu.py always use the path function : `png1 = resource_path(r'./path/to/the/png')`



> > can I add these pngs in the pyinstaller command or do they need to exist in the "/icon/"-folder which would be a problem for the standalone exe we worked towards
> 
> if they are in their own folder then just add this to pyinstaller `--add-data "./folder_name;folder_name/"` But most importantly when referencing them inside ymu.py always use the path function : `png1 = resource_path(r'./path/to/the/png')`

Thanks for the help but I already figured it out, I also reorganized the folders now there is a main "assets" folder containing the splash.png, "icon"-folder and "img"-folder

**Comment by NiiV3AU** [comment]
`v1.0.3` now realeased. Im really pleased how this project turned out, Id never have thought that it would get such big interest in the YimMenu discussions and also I would never have imageined that its going to be full launcher for YimMenu.

Special thanks to you without your help YMU would't be this far.

Im tuned for further additions like adding your ymu_updater, making a button to launch gta, or a Lua-Tab where you can dowload the most famous lua script for YimMenu and update it there

**Comment by NiiV3AU** [comment]
> All thanks to you for creating it and coming forward with it. You didn't keep it to yourself, you actually wanted to share it with the community so thank you.

❤️ 

> I'm also thinking of the same things. Mainly thinking about Lua at the moment because it's suffering lol You can only interact with the scripts and scripts_settings folders and you don't have Internet access 💀 We definitely need a better way to communicate and brainstorm ideas. Would you be willing to create a discord server for YMU?

Yeah I can create a Discord server

**Comment by NiiV3AU** [comment]
Ok I created a simple [YMU Discord Server](https://discord.gg/S4PKmKr22k). Its pretty barebones but for the start its enough.

**Comment by NiiV3AU** [comment]
Oh I didn't notice this message of yours:
> I hope this PR didn't mess with your progress! If it did then I'm sorry I thought you were busy with something else.

No worries, there was no problem. 


> I honestly don't know why because I'm still not good with tkinter or customtkinter but I tried to add the ability to switch between light and dark mode under settings but light mode wasn't working. The code for it is quoted out at the bottom of the file but other than that I couldn't think of something else to add to the settings tab.

Before we can implement a light theme we need to to have dark_image and light_image for all images (folder images as of now) and the labels have different colors for the different themes as well I think

**Comment by xesdoog** [comment]
> EDIT: I corrected your code now It works but we still need to make a light theme for every label as I expected

I've read somewhere that CTk elements can take tuples for colors so you can specify two colors and ctk will automatically switch between them depending on the theme. Would that be better than manually changing every label?

**Comment by NiiV3AU** [comment]
> I've read somewhere that CTk elements can take tuples for colors so you can specify two colors and ctk will automatically switch between them depending on the theme. Would that be better than manually changing every label?

Yup luckily!

**Pull request merged**
