### PR TITLE
Updated Workflow

### PR DESCRIPTION
**Pull request by xesdoog**
- No more autorun.
- Stop removing old releases. (manually remove a release if you're creating a new one with the same version and tag).
- Manually add a version number and tag to the release.
- Add release body (changelog text, link to build, SHA256).

Still not signed and verified but I think I know why. Commits get automatically signed if you were logged in to your Github account in your IDE (I use VSC) while making changes. I was logged in to another account.

### CODE REVIEW

**Comment by NiiV3AU** [comment]
I need help setting up a release with the workflow, I created a token with the permission "Contents" write & read. But I get errors do I need to update the workflow file with [this](https://github.com/softprops/action-gh-release?tab=readme-ov-file#permissions)?

**Comment by xesdoog** [comment]
No you don't need a token. Try copying the workflow file contents somewhere else, remove the file from Github then create a new one and paste everything back. This will also solve the signature issue, your releases will be signed and verified.

**Comment by NiiV3AU** [comment]
I still get the same error code:

> Run softprops/action-gh-release@v2
> 👩‍🏭 Creating new GitHub release for tag v1.0.2...
> ⚠️ GitHub release failed with status: 403
> {"message":"Resource not accessible by integration","documentation_url":"https://docs.github.com/rest/releases/releases#create-a-release"}
> Skip retry — your GitHub token/PAT does not have the required permission to create a release
> Error: Resource not accessible by integration

**Comment by xesdoog** [comment]
> I still get the same error code:
> 
> > Run softprops/action-gh-release@v2
> > 👩‍🏭 Creating new GitHub release for tag v1.0.2...
> > ⚠️ GitHub release failed with status: 403
> > {"message":"Resource not accessible by integration","documentation_url":"[https://docs.github.com/rest/releases/releases#create-a-release"}](https://docs.github.com/rest/releases/releases#create-a-release%22%7D)
> > Skip retry — your GitHub token/PAT does not have the required permission to create a release
> > Error: Resource not accessible by integration

Oh shit, my bad. Yeah you need a personal access token linked to your account I completely forgot about it. 
It's a little bit similar to setting up a discord bot.
[Here's how to create one](https://docs.github.com/en/enterprise-server@2.22/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token)
The workflow file doesn't need any modifications you just have to create that PAT and that's it.

**Comment by NiiV3AU** [comment]
Do you know by any chance which permission I need to grand?

**Comment by xesdoog** [comment]
> Do you know by any chance which permission I need to grand?

Read/Write access to your repositories

**Pull request merged**
